x-apiname: demoApiScaffolding
x-responsetime: 5000

openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'DemoApiScaffolding'
  description: Buy or rent spacecrafts
  contact:
    name: Example Support
    email: admin@admin.com
    url: support.example.com
  license:
    name: BSD-1-Clause
    url: https://opensource.org/license/bsd-1-clause/
  termsOfService: https://example.com/tos

servers:
  - url: https://example-demo.com

paths:
  /spacecrafts/{spacecraftId}:
    parameters:
      - name: spacecraftId
        description: The unique identifier of the spacecraft
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'
        examples:
          response:
            summary: Example response
            description: Description of example
            value: sample
    get:
      description: A GET operation description
      summary: Read a spacecraft
      responses:
        '200':
          description: The spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
              example:
                property: exampleValue

        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                property: exampleValue
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                property: exampleValue
components:
  schemas:
    SpacecraftId:
      description: The unique identifier of a spacecraft
      type: string
    Spacecraft:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/SpacecraftId'
        name:
          type: string
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key

security:
  - ApiKey: []
